### ISSUE TITLE
My refresh pattern

### ISSUE THREAD

**Issue by ageekhere** [mmd123/squid-cache-dynamic_refresh-list#1]
Add any missing refresh patterns from my list
https://forum.netgate.com/topic/99613/improve-custom-refresh-pattern

**Comment by mmd123** [comment]
given my original goal was for MY OWN personal squid proxy list, I KNOW I had added only what applied to mine for my own usage, however, realizing how I did that now, and that this goal was a change AFTER the fact, I'll go through and do this right now, took me a few days to get to it, but I'll do that right now before I work on my game.

**Comment by mmd123** [comment]
changes implemented, committing the new updated file now. thank you @ageekhere
