### ISSUE TITLE
Can you share your squid conf Thank you in advance

### ISSUE THREAD

**Issue by pratikbin** [mmd123/squid-cache-dynamic_refresh-list#9]

**Comment by mmd123** [comment]
I apologize, I only just literally now saw this request.  I am NOT fast to notice things sometimes, so my deepest apologies on noticing this ALMOST A YEAR LATER. sweet heck man.

looking into this now that I've seen this, no I really cannot, given that my personal squid setup is being run on pfsense, there is not an actual squid.conf file as there would be on something like ubuntu, squid is setup differently per the pfsense package it is based upon, so there is not any actual single configuration file like there would be for say ubuntu.  finally looking into it, there's multiple files that comprise the equivalent ubuntu squid.conf.  so there is no real way to share the equivalent of what your asking for.  my apologies, but no, there's not really any way to share what your asking for given it does not exist in that form.

**Comment by pratikbin** [comment]
Got it, thanks.

**Comment by pratikbin** [comment]
BTW Thank you for sharing the list
